language: python
python:
  - 3.8
services:
  - docker

before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t joffreybvn/snake-wars-server:latest .

deploy:

  - provider: script
    script:
      docker push joffreybvn/snake-wars-server:latest;
    on:
      branch: master

  - provider: pypi
    username: "__token__"
    password: "$PYPI_TOKEN"
    on:
      branch: master